# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16jdKmuCgkRSrpnXrOKd_MWjXyGFdQ8ox
"""

print ("salom ")